### ISSUE TITLE
Chimera error

### ISSUE THREAD

**Issue by lh12565** [Brian-hongyan/DeepCoSI#1]
Hi, when I run python codes/DeepCoSI_prediction.py pro.pdb pro_out, there is a error:
```
Processing PDB...
Done process.
Detecting cysteines...
3 cysteine(s) detected.
Generating pockets...
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'chimera'
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'chimera'
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'chimera'
Generating pockets done.
Loading previously saved dgl graphs and corresponding data...
Load model ./codes/DeepCoSI_model_v1.pth
number of parameters :  1729471
Traceback (most recent call last):
  File "codes/DeepCoSI_prediction.py", line 190, in <module>
    test_true = np.concatenate(np.array(test_true), 0).flatten()
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```
I have installed the chimera1.13, The error is still there.
Thanks!

**Comment by GavinXZhang** [comment]
Hey, were you able to find a way to fix this?

**Comment by Brian-hongyan** [comment]
Hi, I made some modification in DeepCoSI_prediction.py. Please specify the path for Chimera in line 82 and try it.
