### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GattiMh** [Brian-hongyan/DeepCoSI#2]
Hello!

Working on an M1 mac and I have problems in installing the tool using conda.

Basically, lots of packages are not found.

Like this:

```
ResolvePackageNotFound: 
  - openssl==1.1.1k=h7f98852_1
  - pysocks==1.7.1=py36h06a4308_0
  - cryptography==3.4.7=py36hd23ed53_0
  - xorg-xextproto==7.3.0=h7f98852_1002
  - cairo==1.16.0=h18b612c_1001
  - libpng==1.6.37=hbc83047_0
  - ........

```
As anyone had similar issues and found solutions?

Many thanks

**Comment by Brian-hongyan** [comment]
Hi, thanks for your message. Could you please give full error message here?

**Comment by GattiMh** [comment]
```
conda env create -f DeepCoSI.yml
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
done
Solving environment: failed

ResolvePackageNotFound: 
  - openssl==1.1.1k=h7f98852_1
  - pysocks==1.7.1=py36h06a4308_0
  - cryptography==3.4.7=py36hd23ed53_0
  - xorg-xextproto==7.3.0=h7f98852_1002
  - cairo==1.16.0=h18b612c_1001
  - libpng==1.6.37=hbc83047_0
  - gmp==6.2.1=h2531618_2
  - xorg-libsm==1.2.3=hd9c2040_1000
  - pandas==1.1.5=py36ha9443f7_0
  - scikit-learn==0.24.2=py36ha9443f7_0
  - openh264==2.1.0=hd408876_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - xorg-libxext==1.3.4=h7f98852_1
  - libffi==3.3=he6710b0_2
  - _libgcc_mutex==0.1=conda_forge
  - mkl-service==2.3.0=py36he8ac12f_0
  - boost-cpp==1.68.0=h11c811c_1000
  - dgl-cuda11.1==0.7.1=py36_0
  - setuptools==52.0.0=py36h06a4308_0
  - cffi==1.14.6=py36h400218f_0
  - xorg-xproto==7.0.31=h7f98852_1007
  - pixman==0.38.0=h516909a_1003
  - xorg-libxau==1.0.9=h7f98852_0
  - giflib==5.2.1=h7b6447c_0
  - libuuid==2.32.1=h7f98852_1000
  - brotlipy==0.7.0=py36h27cfd23_1003
  - libwebp-base==1.2.0=h27cfd23_0
  - lcms2==2.12=h3be6417_0
  - dgllife==0.2.6=py36_0
  - pillow==8.3.1=py36h5aabda8_0
  - libxcb==1.13=h7f98852_1003
  - xorg-renderproto==0.11.1=h7f98852_1002
  - libwebp==1.2.0=h89dd481_0
  - glib==2.68.2=h36276a3_0
  - ninja==1.10.2=hff7bd54_1
  - scipy==1.5.2=py36h0b6359f_0
  - mkl_fft==1.3.0=py36h54f3939_0
  - libidn2==2.3.2=h7f8727e_0
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - torchvision==0.9.0=py36_cu111
  - ffmpeg==4.3=hf484d3e_0
  - readline==8.1=h27cfd23_0
  - xorg-kbproto==1.0.7=h7f98852_1002
  - mkl_random==1.1.1=py36h0573a6f_0
  - cudatoolkit==11.1.74=h6bb024c_0
  - sqlite==3.36.0=hc218d9a_0
  - boost==1.68.0=py36h8619c78_1001
  - gnutls==3.6.15=he1e5248_0
  - mkl==2020.2=256
  - numpy-base==1.19.2=py36hfa32c7d_0
  - certifi==2021.5.30=py36h5fab9bb_0
  - pthread-stubs==0.4=h36c2ea0_1001
  - libiconv==1.15=h63c8f33_5
  - pip==21.2.2=py36h06a4308_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - ncurses==6.2=he6710b0_1
  - libxml2==2.9.9=h13577e0_2
  - zlib==1.2.11=h7b6447c_3
  - jpeg==9b=h024ee3a_2
  - tk==8.6.10=hbc83047_0
  - xz==5.2.5=h7b6447c_0
  - pcre==8.44=he1b5a44_0
  - nettle==3.7.3=hbbd107a_1
  - rdkit==2018.09.3=py36h9c20d5c_0
  - python==3.6.13=h12debd9_1
  - xorg-libxrender==0.9.10=h7f98852_1003
  - xorg-libx11==1.7.2=h7f98852_0
  - freetype==2.10.4=h5ab3b9f_0
  - ca-certificates==2021.5.30=ha878542_0
  - libgcc-ng==11.1.0=hc902ee8_8
  - libtasn1==4.16.0=h27cfd23_0
  - lz4-c==1.9.3=h295c915_1
  - xorg-libice==1.0.10=h7f98852_0
  - icu==58.2=hf484d3e_1000
  - fontconfig==2.13.1=he4413a7_1000
  - libgomp==11.1.0=hc902ee8_8
  - intel-openmp==2020.2=254
  - lame==3.100=h7b6447c_0
  - blas==1.0=mkl
  - libtiff==4.2.0=h85742a9_0
  - libuv==1.40.0=h7b6447c_0
  - bzip2==1.0.8=h7b6447c_0
  - pycairo==1.20.1=py36h726f1de_0
  - _openmp_mutex==4.5=1_gnu
  - libunistring==0.9.10=h27cfd23_0
  - torchaudio==0.8.0=py36
  - numpy==1.19.2=py36h54aff64_0
  - pytorch==1.8.0=py3.6_cuda11.1_cudnn8.0.5_0
  - zstd==1.4.9=haebb681_0
  - ld_impl_linux-64==2.35.1=h7274673_9
```

**Comment by Brian-hongyan** [comment]
Hi, GattiMh. Thanks for your message. This might be due to issues with the Conda channel. I've made some changes to DeepCoSI.yml. It works in my system (Linux, Red Hat 4.8.5-44). Please try it again.

**Comment by Brian-hongyan** [comment]
This might also be due to issues with the difference between Linux and macOS. You can try deleting the second equals sign and the content that follows it. Alternatively, you can comment out these packages that can't be installed and then install them manually.

**Comment by dandavies99** [comment]
Hi @Brian-hongyan, thanks for updating the yml. Are you sure the `pip` part still works on your system? I can't see `dgl==0.7.1` on https://pypi.org/project/dgl/#history, so am unsurprisingly seeing: 
```
ERROR: Could not find a version that satisfies the requirement dgl==0.7.1 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2, 0.3, 0.3.1, 0.4rc190819, 0.4rc190821, 0.4rc190822, 0.4rc190823, 0.4rc190824, 0.4rc190826, 0.4rc190902, 0.4rc190903, 0.4rc190904, 0.4rc190905, 0.4rc190906, 0.4rc190908, 0.4rc190909, 0.4rc190910, 0.4rc190911, 0.4rc190912, 0.4rc190915, 0.4rc190916, 0.4rc190917, 0.4rc190918, 0.4rc190920, 0.4rc190921, 0.4rc190923, 0.4rc190924, 0.4rc190927, 0.4rc190928, 0.4rc190929, 0.4rc191001, 0.4rc191003, 0.4rc191004, 0.4rc191005, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.3.post1, 0.4.3.post2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.0.post1, 0.6.1, 0.9.0, 0.9.1, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for dgl==0.7.1
```
Using a more recent version of dgl e.g. 1.1.0 then causes problems because it requires newer versions of Pytorch.

**Comment by Brian-hongyan** [comment]
Hi @dandavies99, thank you very much for pointing out this. I double checked it. You are right that `pip` can not install `dgl==0.7.1` using `pip install dgl==0.7.1` directly. It still works when you just using command like `conda env create -f DeepCoSI.yml`. I guess `Conda` will automatically search it in `dglteam` channel. Maybe something is wrong when I export the yml file so that `dgl==0.7.1` was put in the `pip` part. I have made an update on `DeepCoSI.yml`.
Thanks again.

**Comment by dandavies99** [comment]
Thanks @Brian-hongyan - that makes sense and thanks for updating the yml file.

I am trying to install in a linux Docker container (I have not been able to resolve the dependency conflicts to install on an M1 Mac, unfortunately). The environment is created successfully but I am getting some libxsmm-related errors when trying to run the example and their cause is not very obvious to me. I'm also not sure whether the libfreetype.so errors are ignorable and just related to viewing results with chimera, or are related.

The Dockerfile I am using and full Traceback of the error is below. If you have any suggestions I would really appreciate it, thanks!

Dockerfile (using miniconda on Debian GNU/Linux 11 (bullseye)):

```Dockerfile
FROM --platform=linux/amd64 continuumio/miniconda3
RUN git clone https://github.com/Brian-hongyan/DeepCoSI.git
COPY ./chimera-1.17.3-linux_x86_64.bin DeepCoSI  # Currently installing after starting the container
RUN conda env create -f DeepCoSI/DeepCoSI.yml
```

After activating the environment inside the container:

```python
(DeepCoSI) root@34cbbb2a63d4:/DeepCoSI# python ./codes/DeepCoSI_prediction.py 4hqr.pdb example
Using backend: pytorch
Namespace(job_name='example', n=1, pdb='4hqr.pdb')
mkdir: cannot create directory ‘build/example_pocket’: File exists
Processing PDB...
Done process.
Detecting cysteines...
10 cysteine(s) detected.
Generating pockets...
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/UCSF/Chimera64-1.17.3/share/__main__.py", line 73, in <module>
    value = chimeraInit.init(sys.argv)
  File "/opt/UCSF/Chimera64-1.17.3/share/chimeraInit.py", line 680, in init
    import chimera
  File "/opt/UCSF/Chimera64-1.17.3/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: libfreetype.so.6: cannot open shared object file: No such file or directory
Generating pockets done.
Loading previously saved dgl graphs and corresponding data...
Load model ./codes/DeepCoSI_model_v1.pth
number of parameters :  1729471
Traceback (most recent call last):
  File "./codes/DeepCoSI_prediction.py", line 195, in <module>
    test_true, test_pred, te_keys = run_a_eval_epoch(DeepCoSI_Model, test_dataloader, device)
  File "./codes/DeepCoSI_prediction.py", line 113, in run_a_eval_epoch
    outputs = model(bg1, bg2)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DeepCoSI/codes/DeepCoSI_Model.py", line 599, in forward
    atom_feats_updated = self.pocket_layer(bg1, atom_feats, bond_feats)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DeepCoSI/codes/DeepCoSI_Model.py", line 334, in forward
    node_feats = self.init_context(g, node_feats, edge_feats)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DeepCoSI/codes/DeepCoSI_Model.py", line 211, in forward
    return self.attentive_gru(g, logits, g.edata['he1'], g.ndata['hv_new'])
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DeepCoSI/codes/DeepCoSI_Model.py", line 61, in forward
    g.edata['e'] = edge_softmax(g, edge_logits) * self.edge_transform(edge_feats)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/ops/edge_softmax.py", line 109, in edge_softmax
    eids=eids, norm_by=norm_by)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/backend/pytorch/sparse.py", line 512, in edge_softmax
    return EdgeSoftmax.apply(gidx, logits, eids, norm_by)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py", line 216, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/backend/pytorch/sparse.py", line 354, in forward
    score_max = _gspmm(gidx, 'copy_rhs', 'max', None, score)[0]
  File "/opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/sparse.py", line 162, in _gspmm
    arg_e_nd)
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 232, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [12:22:56] /opt/dgl/src/array/cpu/./spmm_blocking_libxsmm.h:267: Failed to generate libxsmm kernel for the SpMM operation!
Stack trace:
  [bt] (0) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x41336c03ff]
  [bt] (1) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMRedopCsrOpt<long, float, dgl::aten::cpu::op::CopyRhs<float>, dgl::aten::cpu::op::Max<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x474) [0x41338522e4]
  [bt] (2) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMCmpCsrLibxsmm<long, float, dgl::aten::cpu::op::CopyRhs<float>, dgl::aten::cpu::op::Max<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x8f) [0x41338523af]
  [bt] (3) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMCmpCsr<long, float, dgl::aten::cpu::op::CopyRhs<float>, dgl::aten::cpu::op::Max<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x1f1) [0x41338526e1]
  [bt] (4) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(void dgl::aten::SpMMCsr<1, long, 32>(std::string const&, std::string const&, dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> >)+0x1238) [0x41338735f8]
  [bt] (5) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(dgl::aten::SpMM(std::string const&, std::string const&, std::shared_ptr<dgl::BaseHeteroGraph>, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> >)+0x244e) [0x413389feae]
  [bt] (6) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(+0x7a0e58) [0x41338b0e58]
  [bt] (7) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(+0x7a13f1) [0x41338b13f1]
  [bt] (8) /opt/conda/envs/DeepCoSI/lib/python3.6/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x4133e570c8]
```

**Comment by dandavies99** [comment]
Update: I've got rid of the chimera errors by adding some more packages to my Dockerfile. But the libxsmm errors remain:

```Dockerfile
FROM --platform=linux/amd64 continuumio/miniconda3
RUN git clone https://github.com/Brian-hongyan/DeepCoSI.git
COPY ./chimera-1.17.3-linux_x86_64.bin DeepCoSI
RUN conda env create -f DeepCoSI/DeepCoSI.yml
RUN apt update && apt install -y curl gpg vim
RUN apt-get install ffmpeg libsm6 libxext6 libfreetype6 libxft2  -y
```

**Comment by Brian-hongyan** [comment]
Hi @dandavies99. The libxsmm errors seems come from DGL. The reason of this error is that Libxsmm is not supported in some old versions of CPU. There is a issue about it and there are solutions to it. [https://github.com/dmlc/dgl/issues/3459](url)

**Comment by dandavies99** [comment]
Thanks @Brian-hongyan - in the end, building the docker image on a linux machine rather than on a Mac did the trick.
